version: '2.1'
networks: {}
volumes:
  resin-data: {}
services:
  main:
    container_name: signalk
    build:
      context: .
    restart: always
    network_mode: host
    volumes:
      - 'resin-data:/data'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.balena-api: '1'
  influxdb:
    image: influxdb:alpine
    restart: always
    environment:
      - INFLUXDB_DB="signalk"
      - INFLUXDB_ADMIN_USER="admin"
      - INFLUXDB_ADMIN_PASSWORD="signalk"
    volumes:
      - 'resin-data:/var/lib/influxdb'
    ports:
      - "8086:8086" # API
      - "2003:2003" # Graphite Support
